#!/usr/bin/env python
# encoding: utf-8

import fileinput
import re


def apply_breakpoints(text):
    breakpoint_re = re.compile(r'(\n---\n(.(?!\n---\n))*?)•', re.DOTALL)
    backticks_re = re.compile(r'\n```\s')

    def replacement(match):
        s = match.group(1)

        if len(backticks_re.findall(s)) % 2 == 1:
            separator = '\n```\n'
        else:
            separator = '\n'

        return s + separator + s

    old_text = None
    new_text = text

    while new_text != old_text:
        old_text = new_text
        new_text = breakpoint_re.sub(replacement, old_text)

    return new_text


def _main():
    text = ''
    for line in fileinput.input():
        text += line

    print apply_breakpoints(text),

if __name__ == '__main__':
    _main()
